/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./app/**/*.{js,ts,jsx,tsx}",
    "./pages/**/*.{js,ts,jsx,tsx}",
    "./components/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class", // enable class-based dark mode
  theme: {
    extend: {
      colors: {
        bordercolor: "#F1F1F1",
        checkboxborder: "#CED4DA",
        bggray: "#F2F3F4",
        graytext: "#ADADAD",
        ratingtext: "#B6B6B6",
        inputtext: "#838383",
        advertistext: "#242424",
        recipetext:"#777777",
        regalblue: "#253D4E",
        bgbrown: "#7E7E7E",
        bgfruit1: "#F4F6FA",
        bgfruit2: "#FEEFEA",
        bgfruit3: "#F2FCE4",
        bgfruit4: "#FFFCEB",
        bgfruit5: "#ECFFEC",
        bgfruit6: "#FFF3EB",
        bgfruit7: "#FFF3FF",
        shopbtn: "#3BB77E",
        progessbtn: "#BCE3C9",
        cartbtn: "#DEF9EC",
        productborder: "#ECECEC",
        pinktag: "#F74B81",
        bgpink: "#FDE0E9",
        bluetag: "#67BCEE",
        offertext: "#FDC040",
        orangetag: "#F59758",
      },
      fontFamily: {
        sans: ["Inter", "sans-serif"],
        "quick-bold-700": ["Quicksand-Bold"],
        "quick-semibold-600": ["Quicksand-SemiBold"],
        "quick-medium-500": ["Quicksand-Medium"],
        "quick-regular-400": ["Quicksand-Regular"],
        "quick-light-300": ["Quicksand-Light"],
        "lato-regular-400": ["Lato-Regular"],
        "lato-bold-700": ["Lato-Bold"],
      },
      screens: {
        xs: "320px",
        xs375: "410px",
        sm: "480px",
        md: "768px",
        lg: "992px",
        lg1024: "1024px",
        lg1141: "1141px",
        xl: "1220px",
      },
    },
  },
  plugins: [],
};
