import type { NextApiRequest, NextApiResponse } from "next";

const data = {
  popluarproducts: [
    {
      id: "1",
      tag: "Hot",
      image: "/images/product1.png",
      category: "Snack",
      title: "Seeds of Change Organic Quinoa, Brown, & Red Rice",
      ratingimage: "/svgs/rating.svg",
      rating: "(4.0)",
      by: "NestFood",
      newPrice: 28.85,
      oldPrice: 32.8,
      cartimage: "/svgs/cart.svg",
      cart: "Add",
    },
    {
      id: "2",
      tag: "Sale",
      image: "/images/product2.png",
      category: "Hodo Foods",
      title: "All Natural Italian-Style Chicken Meatballs",
      ratingimage: "/svgs/rating.svg",
      rating: "(3.5)",
      by: "Stouffer",
      newPrice: 52.85,
      oldPrice: 55.8,
      cartimage: "/svgs/cart.svg",
      cart: "Add",
    },
    {
      id: "3",
      tag: "New",
      image: "/images/product3.png",
      category: "Snack",
      title: "Angie’s Boomchickapop Sweet & Salty Kettle Corn",
      ratingimage: "/svgs/rating.svg",
      rating: "(4.0)",
      by: "StarKist",
      newPrice: 48.85,
      oldPrice: 52.8,
      cartimage: "/svgs/cart.svg",
      cart: "Add",
    },
    {
      id: "4",
      tag: "",
      image: "/images/product4.png",
      category: "Vegetables",
      title: "Angie’s Boomchickapop Sweet & Salty Kettle Corn",
      ratingimage: "/svgs/rating.svg",
      rating: "(4.0)",
      by: "StarKist",
      newPrice: 48.85,
      oldPrice: 52.8,
      cartimage: "/svgs/cart.svg",
      cart: "Add",
    },
    {
      id: "5",
      tag: "-14%",
      image: "/images/product5.png",
      category: "Pet Foods",
      title: "Angie’s Boomchickapop Sweet & Salty Kettle Corn",
      ratingimage: "/svgs/rating.svg",
      rating: "(4.0)",
      by: "StarKist",
      newPrice: 48.85,
      oldPrice: 52.8,
      cartimage: "/svgs/cart.svg",
      cart: "Add",
    },
    {
      id: "3",
      tag: "New",
      image: "/images/product3.png",
      category: "Snack",
      title: "Angie’s Boomchickapop Sweet & Salty Kettle Corn",
      ratingimage: "/svgs/rating.svg",
      rating: "(4.0)",
      by: "StarKist",
      newPrice: 48.85,
      oldPrice: 52.8,
      cartimage: "/svgs/cart.svg",
      cart: "Add",
    },
    {
      id: "1",
      tag: "Hot",
      image: "/images/product1.png",
      category: "Snack",
      title: "Seeds of Change Organic Quinoa, Brown, & Red Rice",
      ratingimage: "/svgs/rating.svg",
      rating: "(4.0)",
      by: "NestFood",
      newPrice: 28.85,
      oldPrice: 32.8,
      cartimage: "/svgs/cart.svg",
      cart: "Add",
    },
    {
      id: "2",
      tag: "Sale",
      image: "/images/product2.png",
      category: "Hodo Foods",
      title: "All Natural Italian-Style Chicken Meatballs",
      ratingimage: "/svgs/rating.svg",
      rating: "(3.5)",
      by: "Stouffer",
      newPrice: 52.85,
      oldPrice: 55.8,
      cartimage: "/svgs/cart.svg",
      cart: "Add",
    },
    {
      id: "5",
      tag: "-14%",
      image: "/images/product3.png",
      category: "Meats",
      title: "Angie’s Boomchickapop Sweet & Salty Kettle Corn",
      ratingimage: "/svgs/rating.svg",
      rating: "(4.0)",
      by: "StarKist",
      newPrice: 48.85,
      oldPrice: 52.8,
      cartimage: "/svgs/cart.svg",
      cart: "Add",
    },
    {
      id: "2",
      tag: "Sale",
      image: "/images/product2.png",
      category: "Fruits",
      title: "All Natural Italian-Style Chicken Meatballs",
      ratingimage: "/svgs/rating.svg",
      rating: "(3.5)",
      by: "Stouffer",
      newPrice: 52.85,
      oldPrice: 55.8,
      cartimage: "/svgs/cart.svg",
      cart: "Add",
    },
  ],
};

export default function handler(req: NextApiRequest, res: NextApiResponse) {
  const { id } = req.query;
  const product = data.popluarproducts.find((p) => p.id === id);

  if (!product) {
    res.status(404).json({ message: "Product not found" });
    return;
  }

  res.status(200).json(product);
}
